name: Build Android APK with AdMob
run-name: Build Celestial Oracle Android App 🚀

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Setup Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 4. Install dependencies + AdMob plugin
      - name: Install dependencies
        run: |
          npm install
          npm install @capacitor-community/admob

      # 5. Build Vite app
      - name: Build Vite app
        run: npm run build

      # 6. Initialize Capacitor
      - name: Initialize Capacitor
        run: |
          npx cap init "Celestial Oracle" "com.celestial.oracle" --web-dir=dist || echo "Already initialized"

      # 7. Add Android platform
      - name: Add Android platform
        run: npx cap add android || echo "Android already added"

      # 8. Sync Capacitor
      - name: Sync Capacitor
        run: npx cap sync android

      # 9. Configure AdMob in AndroidManifest
      - name: Configure AdMob
        run: |
          # Add AdMob App ID to AndroidManifest.xml
          sed -i '/<application/a \        <meta-data\n            android:name="com.google.android.gms.ads.APPLICATION_ID"\n            android:value="ca-app-pub-3940256099942544~3347511713"/>' android/app/src/main/AndroidManifest.xml
          echo "✅ AdMob configured in AndroidManifest"

      # 10. Remove adaptive icon XML files that override PNGs
      - name: Remove XML icon overrides
        run: |
          rm -rf android/app/src/main/res/mipmap-anydpi-v26/
          echo "✅ Removed adaptive icon XML overrides"

      # 11. Replace all Android icons
      - name: Replace Android icons
        run: |
          # Create all necessary directories
          mkdir -p android/app/src/main/res/mipmap-mdpi
          mkdir -p android/app/src/main/res/mipmap-hdpi
          mkdir -p android/app/src/main/res/mipmap-xhdpi
          mkdir -p android/app/src/main/res/mipmap-xxhdpi
          mkdir -p android/app/src/main/res/mipmap-xxxhdpi
          
          # Copy your custom icon to all densities
          cp resources/icon.png android/app/src/main/res/mipmap-mdpi/ic_launcher.png
          cp resources/icon.png android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
          cp resources/icon.png android/app/src/main/res/mipmap-hdpi/ic_launcher.png
          cp resources/icon.png android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
          cp resources/icon.png android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
          cp resources/icon.png android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
          cp resources/icon.png android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
          cp resources/icon.png android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
          cp resources/icon.png android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
          cp resources/icon.png android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
          
          echo "✅ Icons replaced successfully"

      # 12. Make gradlew executable
      - name: Make gradlew executable
        run: chmod +x android/gradlew

      # 13. Build debug APK
      - name: Build debug APK
        run: cd android && ./gradlew assembleDebug --stacktrace

      # 14. Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: celestial-oracle-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 14
