name: Build Android APK
run-name: Build Celestial Oracle Android App 🚀

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Setup Java (required for Android)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 4. Install dependencies (includes sharp)
      - name: Install dependencies
        run: npm install

      # 5. Build Vite app
      - name: Build Vite app
        run: npm run build

      # 6. Initialize Capacitor (first time only)
      - name: Initialize Capacitor
        run: |
          npx cap init "Celestial Oracle" "com.celestial.oracle" --web-dir=dist || echo "Already initialized"

      # 7. Add Android platform
      - name: Add Android platform
        run: npx cap add android || echo "Android already added"

      # 8. Generate Android icons from resources/icon.png
      - name: Generate Android icons
        run: node scripts/generate-android-icons.cjs

      # 9. Sync Capacitor
      - name: Sync Capacitor
        run: npx cap sync android

      # 10. Make gradlew executable
      - name: Make gradlew executable
        run: chmod +x android/gradlew

      # 11. Build debug APK
      - name: Build debug APK
        run: cd android && ./gradlew assembleDebug --stacktrace

      # 12. Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: celestial-oracle-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 14
